name: Construir APK Android

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Configurar Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0' # O usa 'stable'
        channel: 'stable'

    - name: Instalar dependencias
      run: flutter pub get

    - name: Construir APK (Release)
      run: flutter build apk --release --no-tree-shake-icons

    - name: Subir APK a GitHub
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
